"""Map of filenames → semantic keys. Paths are relative to zip root (date-prefix stripped)."""

KNOWN: dict[str, str] = {
    # ── Core (zip root) ──────────────────────────────────────────────────────
    "cluster_health.json":          "cluster_health",
    "cluster_stats.json":           "cluster_stats",
    "cluster_settings.json":        "cluster_settings",
    "cluster_state.json":           "cluster_state",
    "nodes_stats.json":             "nodes_stats",
    "nodes_info.json":              "nodes_info",
    "nodes.json":                   "nodes",
    "nodes_usage.json":             "nodes_usage",
    "indices_stats.json":           "indices_stats",
    "indices.json":                 "indices",
    "settings.json":                "index_settings",
    "mapping.json":                 "mapping",
    "segments.json":                "segments",
    "alias.json":                   "aliases",
    "fielddata_stats.json":         "fielddata_stats",
    "pending_tasks.json":           "pending_tasks",
    "shards.json":                  "shards",
    "recovery.json":                "recovery",
    "allocation.json":              "allocation",
    "allocation_explain.json":      "allocation_explain",
    "shard_stores.json":            "shard_stores",
    "master.json":                  "master",
    "version.json":                 "version",
    "plugins.json":                 "plugins",
    "ilm_explain.json":             "ilm_explain",
    "template.json":                "templates",
    "component_template.json":      "component_templates",
    "index_template.json":          "index_templates",
    "pipeline.json":                "pipelines",
    "tasks.json":                   "tasks",
    "dangling_indices.json":        "dangling_indices",
    "deprecation_info.json":        "deprecation_info",
    "internal_health.json":         "internal_health",
    "licenses.json":                "licenses",
    "repositories.json":            "repositories",
    "snapshot.json":                "snapshots",
    "remote_cluster_info.json":     "remote_clusters",

    # ── Commercial (commercial/ subdirectory) ─────────────────────────────────
    "commercial/data_stream.json":                  "data_streams",
    "commercial/ilm_policies.json":                 "ilm_policies",
    "commercial/ilm_explain_only_errors.json":      "ilm_errors",
    "commercial/ilm_status.json":                   "ilm_status",
    "commercial/slm_policies.json":                 "slm_policies",
    "commercial/slm_stats.json":                    "slm_stats",
    "commercial/enrich_policies.json":              "enrich_policies",
    "commercial/transform.json":                    "transforms",
    "commercial/transform_stats.json":              "transform_stats",
    "commercial/ml_anomaly_detectors.json":         "ml_jobs",
    "commercial/ml_stats.json":                     "ml_job_stats",
    "commercial/ml_memory_stats.json":              "ml_memory",
    "commercial/ml_trained_models.json":            "ml_models",
    "commercial/ml_trained_models_stats.json":      "ml_model_stats",
    "commercial/inference.json":                    "inference_endpoints",
    "commercial/ccr_stats.json":                    "ccr_stats",
    "commercial/ccr_follower_info.json":            "ccr_followers",
    "commercial/searchable_snapshots_stats.json":   "searchable_snapshots",
    "commercial/watcher_stats.json":                "watcher",
    "commercial/security_roles.json":               "security_roles",
    "commercial/security_users.json":               "security_users",
    "commercial/xpack.json":                        "xpack",
    "commercial/autoscaling_capacity.json":         "autoscaling",
    "commercial/connectors.json":                   "connectors",
}
